MyMemory/MyMemory.xcodeproj/project.pbxproj
MyMemory/MyMemory/View/Authentication/RegisterView.swift

[ADD]
* Authentication 폴더에 RegisterView추가
* 작업한 View를 먼저 올리기전에 테스트겸 해봤습니다

[Add] RegisterView 추가

---

MyMemory/MyMemory.xcodeproj/project.pbxproj
MyMemory/MyMemory/View/Authentication/RegisterView.swift
MyMemory/MyMemory/View/Authentication/RegisterViewModel.swift

https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/81345604/b5164edc-92b2-485b-a36e-aeac4c587215
[Refactoring] 리뷰반영 업데이트
* RegisterViewModel 중복삭제
* Spacer(minlength:)를 이용해서 다중 Spacer() 정리 및 삭제

[Refactoring] 리뷰반영 업데이트

---

MyMemory/MyMemory/View/Authentication/RegisterView.swift
MyMemory/MyMemory/View/Authentication/RegisterViewModel.swift

[Feat] 
* userCreate함수를 만들었습니다
* Auth를 이용한 유저등록 기능
* putData를 이용해서 유저 프로필은 storage에 저장하고 jpg형식으로 형변환하였습니다
* 위 내용들 외에도 유저의 이름이나 고유ID값 등을 store에 저장하였습니다. Store에 users콜렉션 안에 유저정보를 담도록하였습니다

[Feat] 파이어베이스 회원가입 구현

---

MyMemory/MyMemory/View/Authentication/RegisterViewModel.swift

[Hotfix]
* 파이어베이스 Store에 비밀번호를 저장까지 저장해버려서 위 항목을 삭제하였습니다
* 기타 오타를 수정하였습니다

[Hotfix] Store 비밀번호항목 삭제

---

MyMemory/MyMemory.xcodeproj/project.pbxproj
MyMemory/MyMemory/Cluster/Clustering.swift
MyMemory/MyMemory/MyMemory.entitlements
MyMemory/MyMemory/Shared/LoadingManager.swift
MyMemory/MyMemory/Shared/LocationsHandler.swift
MyMemory/MyMemory/View/Components/LoadingView.swift
MyMemory/MyMemory/View/Components/Memo/MemoCell.swift
MyMemory/MyMemory/View/Components/Memo/MemoListView.swift
MyMemory/MyMemory/View/Components/TopBarAddress.swift
MyMemory/MyMemory/View/Detail/DetailViewComponent/GIFView.swift
MyMemory/MyMemory/View/Main/MainTabView.swift
MyMemory/MyMemory/View/Main/MainView.swift
MyMemory/MyMemory/View/Main/MemoMapView.swift
MyMemory/MyMemory/View/Map/KakaoMap.swift
MyMemory/MyMemory/View/Map/MainMapView.swift
MyMemory/MyMemory/View/Map/MainMapViewModel.swift
MyMemory/MyMemory/View/Map/Subviews/FileterListView.swift
MyMemory/MyMemory/View/Post/PostView.swift

Refactoring/minor UI fix

---

MyMemory/MyMemory.xcodeproj/project.pbxproj
MyMemory/MyMemory/View/Authentication/LoginView.swift
MyMemory/MyMemory/View/Authentication/LoginViewModel.swift
MyMemory/MyMemory/ViewModel/Authentication/AuthViewModel.swift

[ADD]
* LoginViewModel 파일안에 AppleSigninButton에 사용할 뷰를 추가하였습니다
* AuthViewModel 파일안에 authenticate(), randomNonceString(), sha256() 등 애플 로그인에 필요한 함수와 보안관련된 함수를 추가하였습니다
[REFACTORING]
* LoginView 파일의 애플버튼구현 부분을 삭제하고 새로 만들었습니다
-------------------------------------------------------------
아셔야할 사항들
* 애플 로그인 성공 후 바로 맵뷰로 이동하지않아서, 로그인 후 앱을 한번 종료하시면 이동됩니다
* 애플 로그인 버튼이 탭을 하면 작동하지않고 3~5초 정도 눌러야 작동을 합니다

[Hotfix] 깃 충돌 해결

---

MyMemory/MyMemory.xcodeproj/project.pbxproj
MyMemory/MyMemory/View/Components/Memo/MemoCell.swift
MyMemory/MyMemory/View/Detail/DetailView.swift

[Feat]
- DetailView 추가
- MemoCell에서 onChange로 거리에 따라 isVisible값을 바꾸고 isVisble값을 DetailView로 전달
- isVisible값에 따라 DetailView에서 나타내는 View 다르게
거리가 바뀌면 뷰 끼리 전환되는 거 확인되긴 했는데 오류가 있을수있습니다. 테스트가 필요함!

[Feat]: 거리에 따라 디테일뷰 분기

---

MyMemory/MyMemory.xcodeproj/project.pbxproj
MyMemory/MyMemory/View/Components/Memo/MemoCell.swift
MyMemory/MyMemory/View/Detail/CertificationView.swift
MyMemory/MyMemory/View/Detail/CertificationViewModel.swift
MyMemory/MyMemory/View/Detail/DetailViewComponent/CertificationMap.swift
MyMemory/MyMemory/View/Detail/DetailViewComponent/MiniMap.swift
MyMemory/MyMemory/View/Detail/DetailViewComponent/ProgressBarView.swift

- 메인에서 거리가 멀어도 MemoCell이 바뀌지 않던 문제 수정
- CertificationView >> UI 위치 및 크기 조정
- MemoCell이 제 휴대폰에서 나오지가 않아서 실제 테스트가 불가했습니다. 실제로 잘 작동하는지 확인 필요

[Refactoring]: 기존 코드 정리 및 자잘한 오류 수정

---

MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoList.swift
MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoListCell.swift
MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
MyMemory/MyMemory/View/Authentication/Mypage/MypageViewModel.swift

https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/79817557/3b3c1df1-f757-4376-b691-ea820f8b9f15
- 메모 정렬 중 가까운순도 이에 맞게 수정하였습니다.
- 위치를 획득하는데 시간이 오래걸려서, 추가적인 작업이 필요할 것 같습니다.

[Refactoring]: 마이페이지 메모리스트에서 현재 사용자의 위치와의 거리를 나타내도록 수정하였습니다.

---

MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoListCell.swift
MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
MyMemory/MyMemory/ViewModel/Mypage/MypageViewModel.swift

PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
Issue Number: 해당 없음
- 기존의 currentLocation은 연산프로퍼티를 사용하여 위치가 변경될 때마다 `self.fetchMyMemoList()`를 실행했습니다. 
- 매 위치변경 시마다 네트워킹을 하는 것보다는, 현재 메모들의 거리만 업데이트할 수 있도록 기존의 `fetchCurrentUserLocation()`을 수정하여 `CLLocation?`을 클로저의 return값으로 사용할 수 있도록 했고, 이를 통해 기존의 currentLocation의 값과 비교하며 사용자의 현재 위치가 달라질 경우 사용자와 메모간의 거리가 달라질 수 있도록 하였습니다.
- Mypage에서 아래로 당겨 refresh를 할 때, 기존에 메모 리스트만 불러오던 로직을 사용자의 현재 위치도 업데이트하여 거리 또한 업데이트 될 수 있도록 수정하였습니다.
- refresh시, currentLocation을 nil로 만들어 기존의 거리를 -로 변경 후 새로운 거리로 변경됩니다.
```swift 
// 1. 기존의 사용자와 메모간의 거리를 불러오는 로직 수정
// MypageViewModel.swift
class MypageViewModel: ObservableObject {
...
init() {
...
fetchCurrentUserLocation { location in
if let location = location {
self.currentLocation = location
}
}
}
...
}
```
```swift 
// 2. refresh 시 현재위치 확인 …
```

[Refactoring]: 현재 위치와 메모간의 거리를 불러오는 로직을 수정하였습니다. (피드백 반영)

---

MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoList.swift
MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
MyMemory/MyMemory/ViewModel/Mypage/MypageViewModel.swift

PR 날릴 때 체크 리스트
마이페이지에 페이지네이션 적용했습니다.
Issue Number: #130 
페이지네이션 기능을 마이페이지에 적용했습니다.
#131 참고
---
스크린샷
https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/79817557/f2451a7d-bd3e-456f-8204-1a78b32d99b0
```swift
//예시
```
- 정보 1
- 정보 2

[Refactoring]: 마이페이지 페이지네이션 적용

---

MyMemory/MyMemory/MyMemoryApp.swift
MyMemory/MyMemory/View/Authentication/LoginView.swift
MyMemory/MyMemory/ViewModel/Authentication/AuthViewModel.swift
MyMemory/MyMemory/ViewModel/Mypage/MypageViewModel.swift

PR 날릴 때 체크 리스트
Issue Number: #134 
- Email 로그인 시 에러(로그인 실패)가 발생할 경우 상황에 맞는 알러트창을 띄워줍니다.
- LoginView를 NavigationStack으로 감싸 RegisterView로 이동할 수 있도록 수정했습니다.
- MypageView에서 현재위치를 불러올 때 로딩화면이 나타나지 않도록 수정했습니다.
- LoginView의 fullScreenCover 부분을 삭제하여 무한로딩에 빠지던 현상을 수정했습니다.
- 기존의 login()함수는 Bool 타입을 반환하여 로그인의 성공 유무를 나타냈는데, 이를 String 타입을 반환하도록 수정하였습니다.
- String 타입으로 수정한 이유는 `emailLoginErrorHandler`를 사용하여 로그인 에러 코드에 맞는 메시지를 반환하고, 이를 알러트 문구로 사용하기 위해서 입니다.
```swift
func login(withEmail email: String, password: String) async -> String? {
do {
let result = try await Auth.auth().signIn(withEmail: email, password: password)
self.userSession = result.user
self.fetchUser()
return nil
} catch {
let errorMessage = self.emailLoginErrorHandler(error: error as NSError)
return errorMessage
}
}
```
```swift
func …
```

[Refactoring/loginview]: Email 로그인 실패 시 그냥 dismiss되는 부분 수정 및 추가 작업

---

MyMemory/MyMemory.xcodeproj/project.pbxproj
MyMemory/MyMemory.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MyMemory/MyMemory/MyMemoryApp.swift
MyMemory/MyMemory/Resource/Configure/GoogleService-Info.plist
MyMemory/MyMemory/Source/API/MemoService.swift
MyMemory/MyMemory/Source/Shared/LocationsHandler.swift
MyMemory/MyMemory/Source/Shared/PushNotification.swift
MyMemory/MyMemory/View/Map/MainMapView.swift
MyMemory/fastlane/report.xml

PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
Push notification을 개발해보았습니다.
우선 로직은 다음과 같아요!
1. 30초마다 현재 위치를 가지고 반경 50미터(수정가능)내의 메모들을 fetch
2. 메모들 중 가장 최신 메모를 하나 가져와서 그 내용을 가지고 UUID를 담아 Push notification 등록
3. push notification 전송
4. 클릭 시 UUID를 가지고 다시 메모 fetch
5. fetch된 메모가 정상적인 경우 navigation으로 메모 디테일 뷰로 이동
이런 순서로 진행됩니다.
수신할 때
```swift
// in LocationsHandler.swift
///  Push 서버에 쿼리 날리는 부분입니다. location기준으로 특정 영역(50미터) 이내의 메모들 중 가장 최신 메모를 선택했어요
/// - Parameters:
///   - location : 위치값입니다 CLLocation
/// - Returns: void, 메모 성공하면 push 를 보냅니다.
func sendQueryToServer(with location: CLLocation) {
let content = UNMutableNotificationContent()
Task{
do {
if let memo = try await MemoService.shared.fetchPushMemo(in: location) {
content.title = "근처에 새로운 메모가 있어요!"
content.body = "\(memo.title)" …
```

[Feat] Push notification

---

MyMemory/MyMemory.xcodeproj/project.pbxproj
MyMemory/MyMemory/Source/API/AuthService.swift
MyMemory/MyMemory/Source/API/MemoService.swift
MyMemory/MyMemory/Source/Components/Memo/MemoCard.swift
MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
MyMemory/MyMemory/Source/Model/User.swift
MyMemory/MyMemory/View/Authentication/Profile/MypageTopView.swift
MyMemory/MyMemory/View/Authentication/Profile/OtherUserTopView.swift
MyMemory/MyMemory/View/Authentication/Profile/ProfileView.swift
MyMemory/MyMemory/View/Authentication/Profile/UserStatusCell.swift
MyMemory/MyMemory/View/Authentication/ProfileEditView.swift
MyMemory/MyMemory/View/Detail/MemoDetailView.swift
MyMemory/MyMemory/View/Map/MainMapView.swift
MyMemory/MyMemory/View/Post/Subviews/PostViewFooter.swift
MyMemory/MyMemory/View/Setting/SettingView.swift
MyMemory/MyMemory/View/Setting/Style/ThemeView.swift
MyMemory/MyMemory/ViewModel/Authentication/AuthViewModel.swift
MyMemory/MyMemory/ViewModel/Authentication/ProfileEditViewModel.swift
MyMemory/MyMemory/ViewModel/Detail/DetailViewModel.swift
MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
MyMemory/MyMemory/ViewModel/Profile/MypageViewModel.swift
MyMemory/MyMemory/ViewModel/Profile/OtherUserViewModel.swift

PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
현재 많은 부분에서 AuthViewModel을 가지고 user형상 관리를 작업하고 있는데, 이러면 메모리에 AuthViewModel이 늘상 떠있는 문제가 있습니다.
이렇게 되면, AuthViewModel이라는 클래스가 작업하는 내용이 불명확해집니다.
그래서 공용으로 많이 필요한 currentUser그리고 Usersession을 비롯해서, following 관련 로직들을 분리하였고, 해당 부분을 AuthService로 따로 뺐습니다.
```swift
final class AuthService: ObservableObject {
static let shared = AuthService()
@Published var userSession: FirebaseAuth.User?
@Published var currentUser: User?
@Published var isCurrentUserLoginState: Bool
@Published var followerCount: Int = 0
@Published var followingCount: Int = 0
@Published var isFollow: Bool = false
func signout() -> Bool
func checkUser(userID: String) async -> Bool 
func fetchUser()
func fetchUser(completion: @escaping (User?) -> Void)
func memoCreatorfetchUser(uid: String, …
```

[리팩토링] AuthViewModel을 무분별하게 사용하는 부분을 수정했어요

---

MyMemory/MyMemory/View/Post/PostView.swift

PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
포스트뷰에서 environment object를 넘겨받지못해서 생긴 에러였습니다.
```swift
LoginView().environmentObject(AuthViewModel())
```
---

[Hotfix] 포스트뷰에서 로그인시도시 에러해결

---

MyMemory/MyMemory/View/Main/MainTabView.swift

PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
탭바의 배경이 투명해지는 오류를 수정했습니다.
```swift
Group {
}
.toolbarBackground(.visible, for: .tabBar)
```
TabView { } 내부의 요소들을 그룹으로 묶고, 탭뷰가 아닌 그룹의 modifier로 `.toolbarBackground`를 추가합니다.

[Fix]: 탭바 투명화 수정

---

MyMemory/MyMemory/View/Authentication/RegisterView.swift
MyMemory/MyMemory/View/Setting/SettingMenu/WithdrawalView.swift
MyMemory/MyMemory/View/Setting/SettingView.swift
MyMemory/MyMemory/View/Setting/SubViews/SettingMenuCell.swift
MyMemory/MyMemory/View/Setting/SubViews/TermsView.swift

PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
- 회원가입 뷰의 이메일 TextField 부분의 키보드 타입을 이메일로 설정하였습니다.
- 설정 뷰의 약관들을 웹뷰와 연동하였습니다.
- 설정화면과 회원탈퇴 화면을 최신 디자인에 맞게 변경했습니다.
- 기존의 보라색이던 버튼 색상을 accent color로 변경하였습니다.
- enum 타입인 `KindOfTerms`를 만들어 약관이 추가되더라도 편하게 관리할 수 있도록 작업했습니다.
- `UIViewRepresentable`을 사용하여 웹뷰를 구성했습니다.
```swift
import SwiftUI
import WebKit
enum KindOfTerms: String {
case use = "use"
case privacy = "privacy"
}
struct TermsView: View {
var kindOfTerms: KindOfTerms
var body: some View {
VStack {
switch kindOfTerms {
case .use:
TermsWebView(urlToLoad: "https://lucky-sycamore-c73.notion.site/af168c49a93b4fa48830d5bc0512dcb5")
case .privacy:
TermsWebView(urlToLoad: "https://lucky-sycamore-c73.notion.site/12bd694d0a774d2f9c167eb4e7976876")
}
}
.customNavigationBar(
centerView: {
switch …
```

[Refactoring]: 설정 뷰와 회원탈퇴 뷰의 디자인을 최신화했습니다.

---

MyMemory/MyMemory/View/Authentication/MyPage/MyPageView.swift

PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
분기처리 하여 로그인이 아닌 상태에서 마이페이지 접근 시 화면을 수정했습니다.
```swift
// ex). New feature
```
---
```swift
//예시
```
- 정보 1
- 정보 2

[Refactoring]: 로그인이 아닌 상태에서 마이페이지 접근 시 화면을 수정했습니다.

---

MyMemory/MyMemory.xcodeproj/project.pbxproj

PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
이 PR에 대해 간략하게 소개해주세요!
```swift
// ex). New feature
```
---
스크린샷
```swift
//예시
```
- 정보 1
- 정보 2

[hotfix]: TermsView에 관련된 project파일 수정

---

MyMemory/MyMemory.xcodeproj/project.pbxproj
MyMemory/MyMemory/MyMemoryDebug.entitlements
MyMemory/MyMemory/Resource/Configure/MyMemory.entitlements
MyMemory/MyMemory/View/Authentication/GoogleSocialRegisterView.swift
MyMemory/MyMemory/View/Authentication/RegisterView.swift
MyMemory/MyMemory/View/Authentication/SocialRegisterView.swift

PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
Refactoring
박스밖으로 글자가 삐져나가서 박스를 VStack크기에 따라 길이가 바뀌도록 변경하였습니다
```swift
.background(Rectangle().stroke())
```
---

[refactoring] 영어/한글의 다른 글자수로인한 어색한 개인정보약관 박스를 수정하였습니다

---

MyMemory/MyMemory.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MyMemory/MyMemory/View/Authentication/LoginView.swift
MyMemory/MyMemory/ViewModel/Authentication/AuthViewModel.swift

PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
이 PR에 대해 간략하게 소개해주세요!
```swift
Task {
if await viewModel.checkUser(credential: credential ){
AuthService.shared.signout()
self.isNewAppleUser = true
} else {
presentationMode.wrappedValue.dismiss()
}
}
```
기존처럼 값을 다른함수에서 받는것이 아닌 checkUser함수안에서 묶어서 한번에 실행시키고 try await을 하는식으로 고쳤습니다.
덕분에 필수값을 받지않을상태로 코드가 진행되는것을 막아서 원하는 방식으로 동작하게되었습니다
---
스크린샷
```swift
//예시
```
- 정보 1
- 정보 2

[fix] AuthViewModel, LoginView 수정

---

MyMemory/MyMemory.xcodeproj/project.pbxproj
MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserEmptyView.swift
MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserProfileView.swift
MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserTopView.swift
MyMemory/MyMemory/View/Detail/MemoDetailView.swift
MyMemory/MyMemory/View/Detail/Subviews/DetailViewMemoMoveButton.swift
MyMemory/MyMemory/View/Detail/Subviews/MoveUserProfileButton.swift
MyMemory/MyMemory/ViewModel/Detail/DetailViewModel.swift
MyMemory/MyMemory/ViewModel/Profile/OtherUser/OtherUserViewModel.swift

- 피그마 디자인에 맞게 수정하였습니다
- 각 페이지 이동 시 화면 상단에 여백이 생기던 버그를 수정했습니다.
- 메모가 없는 경우 EmptyView를 보여주도록 수정했습니다.
PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
Issue Number: #241 
- 피그마 디자인에 맞게 수정하였습니다
- 각 페이지 이동 시 화면 상단에 여백이 생기던 버그를 수정했습니다.
- 메모가 없는 경우 EmptyView를 보여주도록 수정했습니다.
```swift
// ex). New feature
```
---
--- | --- |
```swift
//예시
```
- 정보 1
- 정보 2

[Refactoring]: OtherProfileView의 디자인 및 메서드들을 수정했습니다.

---

MyMemory/MyMemory/View/Authentication/FollowFollowingList.swift
MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserProfileView.swift
MyMemory/MyMemory/View/Authentication/UserStatusCell.swift

PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
OtherUserProfileView의 어색한 부분을 수정했습니다
```swift
// ex). New feature
```
---
스크린샷
```swift
//예시
```
- 정보 1
- 정보 2

[Fix]: OtherUserProfileView의 어색한 부분을 수정했습니다

---

MyMemory/MyMemory.xcodeproj/project.pbxproj
MyMemory/MyMemory/Assets.xcassets/kakao.imageset/Contents.json
MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
MyMemory/MyMemory/Source/Components/MenuTabBar.swift
MyMemory/MyMemory/Source/Shared/ThemeManager.swift
MyMemory/MyMemory/View/Authentication/MyPage/MyPageView.swift
MyMemory/MyMemory/View/Authentication/MyPage/MypageTopView.swift
MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserProfileView.swift
MyMemory/MyMemory/View/Main/MainTabView.swift
MyMemory/MyMemory/View/Map/CommunityTabView.swift
MyMemory/MyMemory/View/Map/CommunityView.swift
MyMemory/MyMemory/View/Map/ListView.swift
MyMemory/MyMemory/View/Map/MainMapView.swift
MyMemory/MyMemory/View/Map/MainSectionsView.swift
MyMemory/MyMemory/View/Map/PlaceView.swift
MyMemory/MyMemory/View/Setting/SettingTabView.swift
MyMemory/MyMemory/View/Setting/SettingView.swift
MyMemory/MyMemory/View/Setting/Style/ThemeView.swift

PR 날릴 때 체크 리스트
어떤 종류의 PR인가요?
- Tabbar를 5개 항목으로 수정했어요.
- UX를 개선했어요.
- 리스트뷰 안에 있던 커뮤니티를 새로운 탭으로 뺐어요.
- 일부 연결되지 않은 페이지들은 제거했어요.
이 PR에 대해 간략하게 소개해주세요!
https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/75136643/191b7898-99d0-4ff1-a1ab-39a29c4e96d3
https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/75136643/c848a8ee-a3d6-45df-8059-ca5c295e02c7

[Refactoring] 사용자 UX를 개선했어요.
